### ISSUE TITLE
add ability to override pydantic based config from cmdline args

### ISSUE THREAD

**Issue by zzsi** [kungfuai/dynaparse#8]
`--model.net.arch 'vit' --model.input_size.0 500 --model.input_size.1 600` should update the config by:

```
model.net.arch = "vit"
model.input_size[0] = 500
model.input_size[1] = 600
```

Proposal:

Similar to https://github.com/kungfuai/dynaparse/blob/8d897814689988f3ad1265098f1027cd62a22bee/bin/config.py#L100

Define a more generic class `BaseModelFromArgs` that has no fields, but two methods: `def from_args(cls, args)` and `def should_ignore_arg(self, argument: str)`. Then in downstream repos, we can do:

```
from dynaparse import BaseModelFromArgs

class PipelineConfig(BaseModelFromArgs):
    def should_ignore_arg(self, argument):
        if argument in ["-c", "--config", "-h", "--help"]:
            return True
        return False
```

**Comment by mwharton3** [comment]
I believe this is already implemented.

To verify:
* Clone this repo in a py3.8 env
* Run `dynaparse init examples/config_example.json` (creates 2 files, `_spec_auto.json` and `_config_auto.json`
* Run `python examples/script.py --spec _spec_auto.json` (this prints out parsed args with defaults from spec)
* Edit `_config_auto.json` and change `float_parameter_1` to 2.0
* Run `python examples/script.py --spec _spec_auto.json --config _config_auto.json`. This should now show that the float param is 2.0.
* Run `python examples/script.py --spec _spec_auto.json --float_parameter_1 3.0`. This should now show that the float param is 3.0. 

I don't currently support both a config AND overriding. If that's desired, we can track that here.

**Comment by mwharton3** [comment]
Complete per convo with ZZ
